# --------------------------------------------------------------------------
# 1. PATHS
# --------------------------------------------------------------------------
paths:
  # Root dir for raw, immutable data (group space)
  data_root: "/uufs/chpc.utah.edu/common/home/george-group1/data-usea"
  
  # Root dir on scratch space for intermediate files (scratch file system)
  scratch_root: "/scratch/general/vast/u1424875/neural-feature-identification-pipeline"

  # Root dir for final reports and figs (home space)
  results_root: "/uufs/chpc.utah.edu/common/home/u1424875/research-projects/neural-feature-identification-pipeline/reports"
  
  # Path to manifest of curated data files
  data_manifest_db: "/uufs/chpc.utah.edu/common/home/u1424875/research-projects/neural-feature-identification-pipeline/data/raw/curated_file_list_jag.db"

# --------------------------------------------------------------------------
# 2. ANALYSIS PARAMETERS
# --------------------------------------------------------------------------
analysis:
  # Complexity of the control task in number of DOFs.
  # Valid options: 1 (ETD2), 
  #                2 (ETD2 + Wrist Rotator), 
  #                3 (ETD2 + Wrist Rotator + Wrist Flexor), 
  #                6 (LUKE + Wrist Rotator + Wrist Flexor), 
  #                8 (TASKA + Wrist Rotator + Wrist Flexor)
  task_dof: 8

  # List of feature sets to generate and compare in the analysis
  feature_sets:
    - "NFR"
    - "SBP-RAW"
  #  - "SBP-CAR"
  #  - "DWT-DB1"
    - "DWT-DB4"
    - "MAV"

  # Parameters for splitting data into training and testing sets
  train_test_split:
    # Proportion of data to use for training (e.g., 0.7 = 70% train, 30% test)
    train_ratio: 0.7
    split_type: "train_first"
    include_combined: False

# --------------------------------------------------------------------------
# 3. NEURAL DECODING PARAMETERS
# --------------------------------------------------------------------------
algorithms:
  # Select the decoding algorithm to use for this analysis run.
  # Future work: mkf_3rd_order, rnn
  decoder: "mkf_1st_order"

  # Parameters for the feature selection algorithm
  feature_selection:
    # The maximum number of features to select
    max_features: 48

    # The minimum correlation threshold between a feature and the kinematics to be considered in the feature selection process.
    min_correlation: 0.30

# --------------------------------------------------------------------------
# 4. FEATURE EXTRACTION PARAMETERS
# --------------------------------------------------------------------------
feature_extraction_params:
  # NFR: Neural Firing Rate
  nfr:
    # Threshold for spike detection as a multiple of the standard deviation of the baseline signals
    spike_threshold_std: -5

  # SBP: Spiking-Band Power (params shared by SBP-RAW and SBP-CAR)
  sbp:
    # The sliding window length in seconds
    window_length_sec: 0.050

    # Bandpass filter parameters
    bpf_order: 2
    hpf_cutoff_hz: 300
    lpf_cutoff_hz: 1000

  # DWT: Discrete Wavelet Transform
  dwt:
    # Largest power of two less than or equal to 300ms@30kHz
    frame_len: 8192

    # According to Baldazzi, the best performer with the least taps (good for real-time). Equivalent to Haar.
    db1_name: 'db1'
    # Typical wavelet used for micro-neurographs aside from sym7
    db4_name: 'db4'

    # Max decomposition levels Values based on wmaxlev(frame_len, db_name) to avoid boundary effects
    db1_levels: 13
    db4_levels: 10

  # MAV: Mean Absolute Value
  mav:
    window_length_sec: 0.300

# --------------------------------------------------------------------------
# 4. ALTAIR VISUALIZATION PARAMETERS
# --------------------------------------------------------------------------
vis:
  num_of_x_points: 660
  kinematics_offset: 1.75
  dwt_subsample_count: 192